id: P009572
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4532
  title: ཞལ་འདོན་གཅེས་བཏུས
  author: ''
  volumes:
    3ed41a00cd8d403cbf7a7acd730f5bc3:
      image_group_id: I1KG4534
      title: ''
      volume_number: 1
      total_pages: 420
