id: P009572
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:38:43.723294
source_metadata:
  id: bdr:W1KG4532
  title: ཞལ་འདོན་གཅེས་བཏུས
  author: ''
  volumes:
    3ed41a00cd8d403cbf7a7acd730f5bc3:
      image_group_id: I1KG4534
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
